### ISSUE TITLE
Rename family to "BhuTuka One" everywhere

### ISSUE THREAD

**Issue by davelab6** [erinmclaughlin/Dotak#1]
Since this is a non-regular (400) weight font, it should be renamed 'Dotak One' in the font info / name table. 

This means that in the future if/when it is expanded to more weights, then that family can actually be called "Dotak". Otherwise we get something like https://www.google.com/fonts/specimen/Lobster+Two / https://www.google.com/fonts/specimen/Exo+2

**Comment by davelab6** [comment]
Do you think "BhuTuka One" is needed?

**Comment by davelab6** [comment]
Also at https://github.com/erinmclaughlin/BhuTuka/ you can edit the summary line to use the new family name:

<img width="619" alt="screen shot 2016-02-26 at 18 10 25" src="https://cloud.githubusercontent.com/assets/261579/13367923/4637db92-dcb4-11e5-8b08-329f6fee0920.png">

**Comment by davelab6** [comment]
@erinmclaughlin ping :)

**Comment by davelab6** [comment]
This issue is not fixed:

<img width="353" alt="screen shot 2016-03-11 at 00 54 21" src="https://cloud.githubusercontent.com/assets/261579/13694499/d4c1d04c-e723-11e5-849c-cf84bff8499d.png">

**Comment by erinmclaughlin** [comment]
hehe, got it!
